### PR TITLE
Upgrade to ghc 7.10.3 and stack 0.1.10.0 (working build)

### LINKED ISSUE #43: Update to 7.10.3
https://mail.haskell.org/pipermail/ghc-devs/2015-December/010736.html

### PR DESCRIPTION
**Pull request by agrif**
This includes the commit in #44 (and thus also closes #43), but it looks like stack has changed how it is released on OSX, so I changed the code to extract the new tarball and pointed it at the correct path.

Now it builds. The GUI should build too, but I don't have any way to sign it.

### CODE REVIEW

**Comment by gbaz** [comment]
@etrepum are you going to do a build based off this?
@agrif if not, if you do the gui build, i can go ahead and sign it. Sound good?

**Comment by etrepum** [comment]
I'm looking into it, if it works I'll sign and do a release

**Comment by etrepum** [comment]
I still have 10.10 on this machine so I couldn't test 10.11, but it works here so can't be any worse.

**Comment by jhenahan** [comment]
Works on latest 10.11 beta for me.

**Comment by gbaz** [comment]
:+1:

**Comment by gbaz** [comment]
@jhenahan are you running with SIP disabled or enabled? I'm hearing reports that apparently this version still ships a cabal that has the /ar issue.

**Comment by jhenahan** [comment]
Ah, I forgot about that. Yes, I've got SIP disabled, last I checked.

**Comment by etrepum** [comment]
I didn't see any updates to Cabal in any of the PRs. I did update stack to the latest.

**Comment by gbaz** [comment]
This PR, which seems closed unmerged, had some cabal related work: https://github.com/ghcformacosx/ghc-dot-app/pull/46/files

**Pull request merged**
